openapi: 3.0.0

info:
  version: 1.0.0
  title: Proyecto STRAPPS COMMUNITY Entidad Calendario
  description: API de la Entidad calendario de STRAPPS COMMUNITY

servers:
  - url: www.strappsconsulting.com
    description: pagina de strapps

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            usuario: Permisos para partes especificas de la api
            instructor: Permisos para partes especificas de la api
            administrador: Todos los permisos

  responses:
    400Error:
      description: Solicitud incorrecta
      content:
        application/json:
          schema:
            type: object
            properties:
              mensaje:
                type: string
                description: Descripcion del error
                example: "Peticion no valida, favor de validar su informacion"
    401Error:
      description: "No autorizado"
      content:
        application/json:
          schema:
            type: object
            properties:
              mensaje:
                type: string
                description: Descripcion del error
                example: "Es necesario autenticar para obtener la respuesta solicitada."

    404Error:
      description: "Recurso no encontrado"
      content:
        application/json:
          schema:
            type: object
            properties:
              mensaje:
                type: string
                description: "Descripcion del error"
                example: "El servidor no pudo encontrar el contenido solicitado"

    500Error:
      description: "Error interno de servidor"
      content:
        application/json:
          schema:
            type: object
            properties:
              mensaje:
                type: string
                description: "Descripcion del error"
                example: "Oppps, no se pudo procesar"
                
  schemas:
  
    calendario:
       type: object
       properties:
          nombre:
            type: string
            example: "SCRUM MASTER"
            description: Nombre del taller
          fecha:
            type: string
            example: 20/05/22
            description: Fecha del taller
          horario:
            type: string
            example: 20:00 A 21:00 HRS
            description: Horario del taller
    fechas:
       type: object
       properties:
          taller:
            type: string
            example: "SCRUM MASTER"
            description: Nombre del taller
          sesion:
            type: array
            description: lista de sesiones
            items:
              type: object
              properties:
                fecha:
                  description: Fechas de sesiones
                  type: string
                  example: "22/01/2022"
      
      

  
                
                

security:
  #- BasicAuth: []
  #- ApiKeyAuth: []
  - OAuth2: []
    #   - read
    #  - write

paths: #puntos finales (rutas) y metodos (verbos) http /Punto final
  #cuando un punto final tenga corchetes significa que nesecita un parametro

  ##codigo de Laureano

  /usuario/estudiante/calendario:
    get:
      tags:
        - Calendario estudiante
      description: Obtiene calendario de talleres del estudiante REVISADO
      summary: Obtiene calendario de talleres 
      operationId: obtenerCalendario
      parameters:

        - name: token
          in: header
          required: true
          description: Token de Inicio de sesión
          schema:
            type: string

      responses:
        "200":     
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calendario' 
                
        "400":
          description: solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Volver intentar

        "401":
          description: Error de autenticacion
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error De Autenticación
                    description: Hubo un error en el proceso
        "500":
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error No Se Ha Podido Procesar, Intente Más Tarde
                    description: Error en el proceso

  /usuario/taller/fecha:
    get:
      tags:
        - Calendario estudiante
      description: Obtiene las fechas del taller del usuario
      summary: Obtiene las fechas del taller
      operationId: obtenerFechas
      parameters:
        - name: token
          in: header
          required: true
          description: Fechas de talleres
          schema:
            type: string

      responses:
        "200":
          description: OK
          content:
            application/json:              
              schema:
                $ref: '#/components/schemas/fechas'
                
        "400":
          description: solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Volver intentar

        "401":
          description: Error de autenticacion
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error De Autenticación
                    description: Hubo un error en el proceso
        "500":
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error No Se Ha Podido Procesar, Intente Más Tarde
                    description: Error en el proceso

    #IVAN - INST-06 - (Obtener lista de los grupos y sus sesiones)

  /calendario/instructor:
    get:
      tags:
        - Calendario instructor
      description: Obtiene las fechas de los talleres de un instructor determinado a traves del idTaller
      summary: Obtener las fechas de los talleres de un instructor
      parameters:
        - name: token
          in: header
          required: true
          description: Token del inicio de sesión
          schema:
            type: string

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: "Lista grupos del instructor"
                items:
                  type: object
                  properties:
                    tema:
                      type: string
                      example: "SCRUM AVANZADO"
                      description: "Tema del taller"
                    idGrupo:
                      type: string
                      example: 1
                      description: Id del grupo
                    horario: 
                      type: string
                      example: "11:00 - 16:00"
                      description: horario del grupo
                    sesiones:
                      description: Lista de fechas de las sesiones
                      type: array
                      items:
                        type: object
                        properties:
                          dia:
                            description: dia de la sesion
                            type: integer
                            example: 22
                          mes:  
                            type: integer
                            example: 05
                            description: Mes de la sesion
                          anio:
                            type: integer
                            example: 2022
                            description: año de la sesion
        "400":
          $ref: "#/components/responses/400Error"

        "401":
          $ref: "#/components/responses/401Error"

        "404":
          $ref: "#/components/responses/404Error"

        "500":
          
          $ref: "#/components/responses/500Error"
