openapi: 3.0.0 

info:
  version: 1.0.0 
  title: Proyecto STRAPPS COMMUNITY 
  description: API de la pagina de STRAPPS COMMUNITY 

  
servers: 
  - url: www.strappsconsulting.com
    description: pagina de strapps

tags: 
  - name: login
    description: Endpoint para las solicitudes de ingreso
  - name: administrador
    description: Endpoint para las solicitudes del administrador
  - name: instructor
    description: Endpoint para las solicitudes del instructor
  - name: usuario
    description: Endpoint para las solicitudes del usuario
    

components: 
  securitySchemes:

    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            usuario: Permisos para partes especificas de la api
            instructor: Permisos para partes especificas de la api
            administrador: Todos los permisos
      
  responses:
    400Error:
      description: Solicitud incorrecta
      content:
        application/json:
          schema:
            type: object
            properties:   
              mensaje:
                type: string
                description: Descripcion del error
                example: 'Peticion no valida, favor de validar su informacion'
    401Error:
      description: 'No autorizado'
      content:
        application/json:
          schema:
            type: object
            properties:   
              mensaje:
                type: string
                description: Descripcion del error
                example: 'Es necesario autenticar para obtener la respuesta solicitada.'      

    404Error:
      description: 'Recurso no encontrado'
      content:
        application/json:
          schema:
            type: object
            properties:   
              mensaje:
                type: string
                description: 'Descripcion del error'
                example: 'El servidor no pudo encontrar el contenido solicitado'

    500Error:
      description: 'Error interno de servidor'
      content:
        application/json:
          schema:
            type: object
            properties:   
              mensaje:
                type: string
                description: 'Descripcion del error'
                example: 'Oppps, no se pudo procesar'

                
security:
  #- BasicAuth: []
  #- ApiKeyAuth: []
  - OAuth2: []
   #   - read
    #  - write

paths: #puntos finales (rutas) y metodos (verbos) http /Punto final
#cuando un punto final tenga corchetes significa que nesecita un parametro
