openapi: 3.0.0 

info:
  version: 1.0.0 
  title: Proyecto STRAPPS COMMUNITY Entidad de  material 
  description: API de la entidad material para STRAPPS COMMUNITY 

  
servers: 
  - url: www.strappsconsulting.com
    description: pagina de strapps

tags: 
  - name: Administrador
    description: Endpoints para las solicitudes del administrador
  - name: Estudiante
    description: Endpoints para las solicitudes del estudiante
      

components: 
  securitySchemes:

    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            usuario: Permisos para partes especificas de la api
            instructor: Permisos para partes especificas de la api
            administrador: Todos los permisos
      
  responses:
    400Error:
      description: Solicitud incorrecta
      content:
        application/json:
          schema:
            type: object
            properties:   
              mensaje:
                type: string
                description: Descripcion del error
                example: 'Peticion no valida, favor de validar su informacion'
    401Error:
      description: 'No autorizado'
      content:
        application/json:
          schema:
            type: object
            properties:   
              mensaje:
                type: string
                description: Descripcion del error
                example: 'Es necesario autenticar para obtener la respuesta solicitada.'      

    404Error:
      description: 'Recurso no encontrado'
      content:
        application/json:
          schema:
            type: object
            properties:   
              mensaje:
                type: string
                description: 'Descripcion del error'
                example: 'El servidor no pudo encontrar el contenido solicitado'

    500Error:
      description: 'Error interno de servidor'
      content:
        application/json:
          schema:
            type: object
            properties:   
              mensaje:
                type: string
                description: 'Descripcion del error'
                example: 'Oppps, no se pudo procesar'
                
security:
  #- BasicAuth: []
  #- ApiKeyAuth: []
  - OAuth2: []
   #   - read
    #  - write

paths: #puntos finales (rutas) y metodos (verbos) http /Punto final
#cuando un punto final tenga corchetes significa que nesecita un parametro


##Descargar material del usuario
  /estudiante/taller/material/{idTaller}:
    get:
      tags: 
      - Estudiante 

      description: Obtiene los materiales del estudiante por el id taller REVISADO
      summary: Obtiene los materiales
      parameters:
        - name: token
          in: header
          required: true
          description: Token del inicio de sesión
          schema:
            type: string
        - name: idTaller
          in: path
          required: true
          description: Id del taller
          schema: 
            type: string


      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: Lista de materiales
                items:
                  type: object
                  properties:
                    urlImagenPreview:
                      type: string
                      example: http://strappsconsulting.com/imagenpreview/1
                      description: Url de la imagen preview
                    urlIcono: 
                      type: string
                      example: http://strappsconsulting.com/imagenicono/1
                      description: Url del icono del archivo
                    nombreArchivo: 
                      type: string
                      example: MATERIAL.pdf
                      description: Nombre de archivo de material
                    urlDescarga: 
                      type: string
                      example: http://strappsconsulting.com/materialdedescarga/1
                      description: Url para descargar material 
                    
        "400":
          description: solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Volver intentar
        '401':
          description: Error de autenticacion
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error De Autenticación
                    description: Hubo un error en el proceso
        '500':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error No Se Ha Podido Procesar, Intente Más Tarde
                    description: Error en el proceso

  /administrador/material:
    post:
      tags:
        - Administrador
      description: Crea nuevo material para grupos. REVISADO
      summary: Crea un material
      requestBody:
        required: true
        content:
           multipart/form-data:
            schema:
              type: object 
              properties:
                idGrupo:
                  type: integer
                  description: Id del grupo
                material:
                  type: string
                  format: binary
                  description: Material de estudio 
                 

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Se guardo correctamente el material
                    description: Mensaje de respuesta correcta
        '400':
          description: No se han obtenido datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: No ha llenado todos los campos
                    description: Faltan campos por llenar
        '401':
          description: Error de la validacion de campos
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: No se han obtenido datos de validacion
                    description: No se han obtenido datos
        '500':
          description: Error de autenticacion
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: No se ha podido procesar correctamente intentelo mas tarde
                    description: No se han obtenido datos

  /administrador/material/{idGrupo}:
    get:
      tags: 
      - Administrador 

      description: Obtiene los materiales del grupo por el id grupo REVISADO
      summary: Obtiene los materiales
      parameters:
        - name: token
          in: header
          required: true
          description: Token del inicio de sesión
          schema:
            type: string
        - name: idGrupo
          in: path
          required: true
          description: Id del grupo
          schema: 
            type: integer


      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: Lista de materiales
                items:
                  type: object
                  properties:
                    id: 
                      type: integer
                      example: 1
                      description: Id del material
                    urlImagenPreview:
                      type: string
                      example: http://strappsconsulting.com/imagenpreview/1
                      description: Url de la imagen preview
                    urlIcono: 
                      type: string
                      example: http://strappsconsulting.com/imagenicono/1
                      description: Url del icono del archivo
                    nombreArchivo: 
                      type: string
                      example: MATERIAL.pdf
                      description: Nombre de archivo de material
                    urlDescarga: 
                      type: string
                      example: http://strappsconsulting.com/materialdedescarga/1
                      description: Url para descargar material 
                    
        "400":
          description: solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Volver intentar
        '401':
          description: Error de autenticacion
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error De Autenticación
                    description: Hubo un error en el proceso
        '500':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error No Se Ha Podido Procesar, Intente Más Tarde
                    description: Error en el proceso
  /administrador/material/{id}:
    delete:
      tags:
        - Administrador
      description: Elimina material por el Id. REVISADO
      summary: Elimina material
      parameters:
          - name: id
            in: path
            required: true
            description: Id material
            example: 1
            schema:
              type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Se elimino correctamente el material
                    description: Mensaje de respuesta correcta
        '400':
          description: No se han obtenido datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: No ha llenado todos los campos
                    description: Faltan campos por llenar
        '401':
          description: Error de la validacion de campos
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: No se han obtenido datos de validacion
                    description: No se han obtenido datos
        '500':
          description: Error de autenticacion
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: No se ha podido procesar correctamente intentelo mas tarde
                    description: Error No Se Ha Podido Procesar, Intente Más Tarde

  #  ---- /ESTUDIANTE  ----------------------------------------
                    
  /estudiante/Taller:
    get:
      tags:
      - Estudiante 
      description: Obiene informacion del taller de cada usuario
      summary: obtener informacion del taller por usuario
      parameters:

        - name: token
          in: header
          required: true
          description: Token del inicio de sesión
          schema:
            type: string
    
             
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    taller: 
                      type: string
                      example: SCRUM MASTER
                      description: Nombre del taller
                      

        "400":
          description: solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Volver intentar
        '401':
          description: Error de autenticacion
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error De Autenticación
                    description: Hubo un error en el proceso
        '500':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error No Se Ha Podido Procesar, Intente Más Tarde
                    description: Error en el proceso   

  /estudiante/taller/material/visualizar:
    get:
      tags:
      - Estudiante 
      description: Obtiene información de material
      summary: Obtiene información del material por usuario
      parameters:

        - name: token
          in: header
          required: true
          description: Token del inicio de sesión
          schema:
            type: string

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nombre del archivo: 
                      type: string
                      example: programacion
                      description: nombre del archivo 
                                        
        "400":
          description: solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Volver intentar
        '401':
          description: Error de autenticacion
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error De Autenticación
                    description: Hubo un error en el proceso
        '500':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error No Se Ha Podido Procesar, Intente Más Tarde
                    description: Error en el proceso
   
  /estudiante/taller/material/descarga:
    get:
      tags:
      - Estudiante 
      description: Obtiene información de la descarga del documento
      summary: Obtiene información del documento del usuario
      parameters:

        - name: token
          in: header
          required: true
          description: Token del inicio de sesión
          schema:
            type: string

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nombre del archivo: 
                      type: string
                      example: programacion
                      description: Nombre del documento                     
        "400":
          description: solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Volver intentar
        '401':
          description: Error de autenticacion
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error De Autenticación
                    description: Hubo un error en el proceso
        '500':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error No Se Ha Podido Procesar, Intente Más Tarde
                    description: Error en el proceso
            
